In [1]:
import pandas as pd
import numpy as np

In [18]:
# Load the training data and test data
training_data = pd.read_csv('./Datasets/train.csv')
test_data = pd.read_csv('./Datasets/test.csv')
test_labels = pd.read_csv('./Datasets/test_data_labels.csv')
# merge the test data with the labels
training_data

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
...,...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa...",1

In [12]:
# Function that accumulates the text from all the news articles -> Pu
# Make a dictionary of key -> title  value -> text and then a list of all the titles that are fake news/real news

# Function that removes all the stop words from the news articles -> Akshay 

# Function that returns a list of the news sources used in each article (citations or source of article) -> Maddie 

# Function that gets the author and publisher from each source -> Ivan

# Function that returns the n most common words from an article. Dictionary: key - common words 
# value - number of times each word appears in an article (depends on removing stop words) -> Bolun

# Construct a feature vector for our training data for the ML model (array of all the text from each article and the label too)
# Use dictionary from method above to assign it a score and decide whether its fake news or not 
# (Akshay - go to OH and ask for help)
# Make sure to test classification accuracy

# Create a Wordle from the text (one that's fake news and one that's real news) -> Bolun

# Get the political affilliation/bias of each article based on the publisher (left, right, center (non political articles))
# -> Ivan 

# Start the UI stuff to figure out whether an article is fake news -> Maddie 

# Return a list of the proper names used in the article -> Maddie/Ivan (use that for the list of news sources)

# Function that returns all the articles election related and whether they were fake news not 
    # Figure out which election had the most fake news

         id  label
0     20800      0
1     20801      1
2     20802      0
3     20803      1
4     20804      1
...     ...    ...
5195  25995      0
5196  25996      1
5197  25997      0
5198  25998      1
5199  25999      0

[5200 rows x 2 columns]